name: Deploy Backend to Render

on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-INSERT_YOUR_SERVICE_ID?key=$RENDER_DEPLOY_KEY
        env:
          RENDER_DEPLOY_KEY: ${{ secrets.RENDER_DEPLOY_KEY }}
